name: effect.dart
description: A powerful Effect library for Dart inspired by Effect-TS, providing functional programming patterns for managing side effects, errors, and dependencies.
version: 0.1.0
homepage: https://github.com/shtse8/effect.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

# Melos configuration
melos:
  name: effect.dart
  packages:
    - .